# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  helloapi:
    image: helloapi
    build:
      context: .
      dockerfile: HelloApi/Dockerfile
    ports:
      - 5000:5273
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
